# Generated by Django 5.0.6 on 2024-07-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_payment_orderplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='Customer',
            new_name='customer',
        ),
    ]
